# For testing and documentation 
# This file is used to define tests, descriptions, and documentation for your models
version: 2

models:
  - name: transform_messages
    description: "This model transforms the medical_data by converting message text to lowercase."
    columns:
      - name: message_id
        description: "Unique identifier for each message."
        tests:
          - not_null
          - unique
      - name: sender_id
        description: "Identifier for the sender of the message."
        tests:
          - not_null
      - name: message_text
        description: "The content of the message."
        tests:
          - not_null
      - name: channel
        description: "The channel through which the message was sent."
      - name: date
        description: "The date and time when the message was sent."
