medical_data_warehouse:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: password
      port: 5432
      dbname: medical_data_warehouse
      schema: public
  target: dev
